<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Clicked</description>
   <name>AprimaEnterprise_Object</name>
   <tag></tag>
   <elementGuidId>5b9c68d0-8a6b-48f1-95da-02fde0a6b4a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectedEnterprise']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id='selectedEnterprise']</value>
   </webElementProperties>
</WebElementEntity>
