<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Clicked</description>
   <name>AprimaEnterprise_Object</name>
   <tag></tag>
   <elementGuidId>658f0fab-439f-4da9-b47f-b76e9103e95b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectedEnterprise']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id='selectedEnterprise']</value>
   </webElementProperties>
</WebElementEntity>
