<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Clicked</description>
   <name>AprimaEnterprise_Object</name>
   <tag></tag>
   <elementGuidId>76835423-d601-4af6-831b-7d3c0e41440e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectedEnterprise']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id='selectedEnterprise']</value>
   </webElementProperties>
</WebElementEntity>
